### ISSUE TITLE
ASSERT failed error

### ISSUE THREAD

**Issue by deekshasinha** [se4u/cylsh#1]
I have complied the package using 'make cython_binding_e2lsh'.

On running the example mentioned in the README, 

> > > import cylsh;
> > > import numpy as np
> > > db=cylsh.LSH(0.9,
> > >                  0.9,
> > >                  np.asarray([[.1, .7, .7],
> > >                             [.11, .69, .7]]),
> > >                  np.asarray([[.1, .7, .7]]),
> > >                  1e6);
> > > print db.query(np.asarray([.1, .7, 0]))

I am getting an ASSERT failed error. The exact error is '_ASSERT failed on line 583, file ../sources/LocalitySensitiveHashing.cpp_'

When I run the above on an IDE (Spyder), the error I get is '_It seems the kernel died unexpectedly. Use 'Restart kernel' to continue using this console._'

**Comment by se4u** [comment]
It seems that the documentation has gotten out of date. I apologize for that.
I was able to run the code by using the following commands

``` bash
   mkdir tmp
   cd tmp
   git clone https://github.com/se4u/cylsh.git
   cd cylsh/E2LSH-0.1
   make cython_binding_e2lsh
   cd sources_py
   python test_api.py 'lsh'  ../sample_data/mnist1k.dts ../sample_data/mnist1k.q 0.8 2 0.9
```

By running this exact sequence of commands I got the following output 

```
   Building DB now
   time taken for building dataset 0.116393
   Query 0: Found 15 NNs with distance 0.800000. First 10 NNs are:
   AssignedRank:  1     Id:      794    distance:0.504293       TrueRank:1      TrueNbr:000794
   AssignedRank:  2     Id:      851    distance:0.657369       TrueRank:2      TrueNbr:000851
   AssignedRank:  3     Id:      327    distance:0.659420       TrueRank:3      TrueNbr:000327
   ...
```

Now unfortunately the code in test_api.py is a bit of a mess and I wont have time to refactor that. 
But I made a file called `mwe_e2lsh.py` that demonstrates the important piece of code.

``` python
from cylsh import LSH
import numpy as np
LSH_OR_MIPS = 'lsh'
dataset = np.loadtxt('../sample_data/mnist1k.dts')
queryset = np.loadtxt('../sample_data/mnist1k.q')
R = 0.8
K = 2
p = 0.9
sample_query = dataset[1:3, :]
# Create LSH Database  
optim_param = LSH.compute_optimal_parameters(                                                                                       
    R, p, dataset, sample_query, 22020096)
db = LSH.init_manually(optim_param, dataset)
# Query LSH Database  
print db.query(queryset[6])
```

Please try this method for instantiating and querying the E2LSH database.

**Comment by deekshasinha** [comment]
Can you please elaborate on what changes need to be made to use this for finding maximum inner product points rather than nearest neighbours ?

_python test_api.py 'lsh'  ../sample_data/mnist1k.dts ../sample_data/mnist1k.q 0.8 2 0.9_
and
_python test_api.py 'mips'  ../sample_data/mnist1k.dts ../sample_data/mnist1k.q 0.8 2 0.9_

give almost exactly the same result.

Similarly, in the mwe_e2lsh.py file, changing  _LSH_OR_MIPS = 'mips'_ from _LSH_OR_MIPS = 'lsh'_ doesn't change the results.

**Comment by se4u** [comment]
Hi, in order to use this for MIPS please compile it using the mips_binding
command.

The reason why the results are the same is because iirc the sample points
in mnist1k are all scaled to have the same same magnitude, in that case
mips and lsh are exactly the same.

I am away from  a computer right now but I'll give an example soon

**Comment by se4u** [comment]
Hi,  please run the following commands to see an example/test of how to use MIPS and LSH.

``` bash
rm -rf tmp
mkdir tmp                                  
cd tmp                                     
git clone https://github.com/se4u/cylsh.git
cd cylsh/E2LSH-0.1                         
make cython_binding_e2lsh                  
cd sources_py
python test_mips.py
python test_lsh.py   
```

`diff test_mips.py test_lsh.py` shows exactly how Neyshabur and Srebro's MIPS algorithms is a very simple tweak on top on E2LSH.

``` diff
25c25
<     LSH_OR_MIPS = 'lsh'
---
>     LSH_OR_MIPS = 'mips'
34c34
< # np.linalg.norm([np.linalg.norm(dataset[i]) - 1 for i in range(1000)])
---
> # np.linalg.norm([np.linalg.norm(dataset[i]) - 1 for i in range(dataset.shape[0])])
43a44,55
>
> data_norms = np.linalg.norm(dataset, axis=1)
> max_norm = max(data_norms)
> dataset = dataset / max_norm
> dataset = np.concatenate(
>     (dataset, np.sqrt(1 - (data_norms / max_norm) ** 2)[:, None]), axis=1)
>
> queryset = np.concatenate(
>     (queryset / np.linalg.norm(queryset, axis=1)[:, None],
>      np.zeros((queryset.shape[0], 1))),
>     axis=1)
```

**Comment by deekshasinha** [comment]
Thanks for the detailed explanation.
